In [1]:
%reload_ext autotime
import pandas as pd
import geopandas as gpd
from glob import glob
import os
from tqdm.auto import tqdm
import statsmodels.formula.api as smf
tqdm.pandas()

/mnt/streetview/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

time: 2.1 s (started: 2026-02-25 12:28:41 +13:00)

In [2]:
pd.set_option('display.max_columns', None)
df = pd.read_csv("results.csv")
LLM_results = pd.read_csv("LLM_results.csv")
new_cols = LLM_results.columns[~LLM_results.columns.isin(df.columns)].tolist()
df = df.merge(LLM_results[new_cols + ["panoid"]], on="panoid")
df = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df.longitude, df.latitude), crs="EPSG:4326").to_crs(2193)
df.to_csv("merged_results.csv", index=False)
df

,Index,pid,n,time,anxiousness,latitude,longitude,geometry,panoid,panolat,panolon,panodate,panothirdparty,source,uploader,green,environment,active_transport,quality,water,obscured,people,cars,bikes,dwellings,shops,offices
0,0,P20001,1,2023-04-25T02:51:42Z,0,-36.924795,174.738044,POINT (1754803.112 5912059.517),IvrcS0W1RlFAlnci-p39XA,-36.924667,174.737908,2012-04,False,launch,NaN,45,medium density residential,True,70,0,30,2,3,1,8,1,0
1,1,P20001,2,2023-04-25T08:43:13Z,0,-36.924801,174.738076,POINT (1754806.011 5912058.736),IvrcS0W1RlFAlnci-p39XA,-36.924667,174.737908,2012-04,False,launch,NaN,45,medium density residential,True,70,0,30,2,3,1,8,1,0
2,2,P20001,3,2023-04-26T02:22:26Z,0,-36.924783,174.738071,POINT (1754805.575 5912060.734),IvrcS0W1RlFAlnci-p39XA,-36.924667,174.737908,2012-04,False,launch,NaN,45,medium density residential,True,70,0,30,2,3,1,8,1,0
3,3,P20001,4,2023-04-26T09:00:53Z,0,-36.924797,174.738123,POINT (1754810.215 5912059.092),IvrcS0W1RlFAlnci-p39XA,-36.924667,174.737908,2012-04,False,launch,NaN,45,medium density residential,True,70,0,30,2,3,1,8,1,0
4,4,P20001,5,2023-04-26T20:36:19Z,3,-36.924771,174.738084,POINT (1754806.75 5912062.109),IvrcS0W1RlFAlnci-p39XA,-36.924667,174.737908,2012-04,False,launch,NaN,45,medium density residential,True,70,0,30,2,3,1,8,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293,1426,P20721,1,2024-05-05T02:00:52Z,1,-36.893455,174.728262,POINT (1753994.828 5915552.341),ftrRbHWdN74ZKSFMEkPscg,-36.893414,174.728087,2024-10,False,launch,NaN,45,medium density residential,True,70,0,30,2,3,1,6,1,0
1294,1427,P20721,2,2024-05-05T07:36:22Z,1,-36.893483,174.728253,POINT (1753993.98 5915549.306),ftrRbHWdN74ZKSFMEkPscg,-36.893414,174.728087,2024-10,False,launch,NaN,45,medium density residential,True,70,0,30,2,3,1,6,1,0
1295,1428,P20721,3,2024-05-05T23:06:27Z,2,-36.845252,174.759951,POINT (1756917.266 5920848.722),CIHM0ogKEICAgICO_7-B_AE,-36.845292,174.759939,2022-06-24,True,photos:street_view_publish_api,Mint Design,45,medium density residential,True,65,0,30,3,2,1,8,1,0
1296,1429,P20721,4,2024-05-06T07:04:57Z,0,-36.845165,174.759885,POINT (1756911.566 5920858.442),CIHM0ogKEICAgICO_-_r1AE,-36.845177,174.759792,2022-06-24,True,photos:street_view_publish_api,Mint Design,45,medium density residential,True,65,0,30,3,2,1,6,1,0
1297,1430,P20721,5,2024-05-06T20:11:18Z,1,-36.845252,174.759953,POINT (1756917.426 5920848.708),CIHM0ogKEICAgICO_7-B_AE,-36.845292,174.759939,2022-06-24,True,photos:street_view_publish_api,Mint Design,45,medium density residential,True,65,0,30,3,2,1,8,1,0

time: 128 ms (started: 2026-02-25 12:28:43 +13:00)

In [3]:
files = glob("nz-*-topo-150k/*.gpkg")
files

['nz-river-polygons-topo-150k/nz-river-polygons-topo-150k.gpkg',
 'nz-river-centrelines-topo-150k/nz-river-centrelines-topo-150k.gpkg',
 'nz-swamp-polygons-topo-150k/nz-swamp-polygons-topo-150k.gpkg',
 'nz-pond-polygons-topo-150k/nz-pond-polygons-topo-150k.gpkg',
 'nz-coastlines-topo-150k/nz-coastlines-topo-150k.gpkg',
 'nz-lake-polygons-topo-150k/nz-lake-polygons-topo-150k.gpkg',
 'nz-spring-points-topo-150k/nz-spring-points-topo-150k.gpkg']

time: 3.16 ms (started: 2026-02-25 12:28:44 +13:00)

In [7]:
water_dict = {}
for f in tqdm(files):
  name = os.path.dirname(f).replace("nz-", "").replace("-topo-150k", "")
  water_gdf = gpd.read_file(f)
  water_gdf.sindex
  water_dict[name] = water_gdf

100%|██████████| 7/7 [00:06<00:00,  1.01it/s]

time: 7.68 s (started: 2026-02-25 12:40:58 +13:00)

In [8]:
def get_closest_water(point):
  closest_distance = 1e10
  closest_name = "?"
  for name, water_gdf in water_dict.items():
    distance = water_gdf.sindex.nearest(point, return_distance=True)[1][0]
    if distance < closest_distance:
      closest_distance = distance
      closest_name = name
  return closest_name, closest_distance

df["water_type"], df["water_distance"] = zip(*df.geometry.progress_apply(get_closest_water))

100%|██████████| 1298/1298 [00:03<00:00, 373.50it/s]

time: 3.49 s (started: 2026-02-25 12:41:09 +13:00)

In [9]:
df.water_type.value_counts()

water_type
river-centrelines    559
lake-polygons        397
coastlines           333
pond-polygons          5
river-polygons         4
Name: count, dtype: int64

time: 6.76 ms (started: 2026-02-25 12:41:13 +13:00)

In [10]:
df.water_distance.describe().apply("{0:.5f}".format)

count       1298.00000
mean        9573.89169
std       127828.54581
min            4.32646
25%          380.74866
50%          703.17936
75%         1110.73890
max      1885737.33112
Name: water_distance, dtype: str

time: 10.3 ms (started: 2026-02-25 12:41:13 +13:00)

In [15]:
df.describe()

,Index,n,anxiousness,latitude,longitude,panolat,panolon,green,quality,water,obscured,people,cars,bikes,dwellings,shops,offices,water_distance
count,1298.000000,1298.000000,1298.000000,1298.000000,1298.000000,1298.000000,1298.000000,1298.000000,1298.000000,1298.0,1298.000000,1298.000000,1298.000000,1298.000000,1298.000000,1298.000000,1298.000000,1.298000e+03
mean,719.953005,6.327427,2.392142,-36.917101,174.677841,-36.917008,174.677765,48.081664,70.261941,0.0,31.999230,2.364407,2.573960,0.988444,7.049307,1.054700,0.051618,9.573892e+03
std,417.914799,4.256959,2.583591,0.323864,1.611795,0.323842,1.611793,7.126641,3.496991,0.0,3.236621,0.481449,0.553533,0.106918,1.139751,0.485023,0.221340,1.278285e+05
min,0.000000,1.000000,0.000000,-44.085607,151.172856,-44.085399,151.172704,45.000000,65.000000,0.0,30.000000,2.000000,1.000000,0.000000,3.000000,0.000000,0.000000,4.326461e+00
25%,356.250000,3.000000,0.000000,-36.925418,174.738329,-36.925592,174.738444,45.000000,70.000000,0.0,30.000000,2.000000,2.000000,1.000000,6.000000,1.000000,0.000000,3.807487e+02
50%,716.500000,5.000000,2.000000,-36.911762,174.754198,-36.911792,174.751777,45.000000,70.000000,0.0,30.000000,2.000000,3.000000,1.000000,8.000000,1.000000,0.000000,7.031794e+02
75%,1088.750000,9.000000,5.000000,-36.894394,174.802860,-36.894184,174.802904,45.000000,75.000000,0.0,35.000000,3.000000,3.000000,1.000000,8.000000,1.000000,0.000000,1.110739e+03
max,1430.000000,20.000000,10.000000,-33.801848,176.251862,-33.801691,176.251412,65.000000,75.000000,0.0,40.000000,3.000000,3.000000,1.000000,12.000000,2.000000,1.000000,1.885737e+06

time: 94.3 ms (started: 2026-02-25 12:41:59 +13:00)

In [16]:
df.to_csv("merged_results.csv", index=False)

time: 91.3 ms (started: 2026-02-25 12:42:12 +13:00)

In [17]:
df.environment.value_counts()

environment
medium density residential    1176
low density residential        122
Name: count, dtype: int64

time: 8.75 ms (started: 2026-02-25 12:42:13 +13:00)

In [18]:
IVs = " + ".join(df.columns[15:])
IVs

'green + environment + active_transport + quality + water + obscured + people + cars + bikes + dwellings + shops + offices + water_type + water_distance'

time: 12.7 ms (started: 2026-02-25 12:42:15 +13:00)

In [19]:
smf.ols(formula=f"anxiousness ~ {IVs}", data=df).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            anxiousness   R-squared:                       0.027
Model:                            OLS   Adj. R-squared:                  0.016
Method:                 Least Squares   F-statistic:                     2.386
Date:                Wed, 25 Feb 2026   Prob (F-statistic):            0.00210
Time:                        12:42:17   Log-Likelihood:                -3055.4
No. Observations:                1298   AIC:                             6143.
Df Residuals:                    1282   BIC:                             6226.
Df Model:                          15
Covariance Type:            nonrobust
=============================================================================================================
                                                coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------
Intercept                                     0.1346      1.124      0.120      0.905      -2.070       2.339
environment[T.medium density residential]     0.7832      0.472      1.658      0.097      -0.143       1.710
active_transport[T.True]                      0.1346      1.124      0.120      0.905      -2.070       2.339
water_type[T.lake-polygons]                  -0.5222      0.195     -2.684      0.007      -0.904      -0.141
water_type[T.pond-polygons]                  -0.6981      1.160     -0.602      0.547      -2.974       1.577
water_type[T.river-centrelines]              -0.0620      0.181     -0.343      0.732      -0.417       0.293
water_type[T.river-polygons]                  1.4033      1.292      1.086      0.278      -1.131       3.938
green                                         0.0479      0.020      2.354      0.019       0.008       0.088
quality                                      -0.0358      0.024     -1.512      0.131      -0.082       0.011
water                                     -4.043e-16   4.68e-16     -0.863      0.388   -1.32e-15    5.14e-16
obscured                                     -0.0126      0.030     -0.424      0.672      -0.071       0.046
people                                        0.3909      0.335      1.166      0.244      -0.267       1.048
cars                                          0.5152      0.300      1.718      0.086      -0.073       1.104
bikes                                        -0.9794      0.841     -1.165      0.244      -2.629       0.670
dwellings                                     0.1251      0.075      1.672      0.095      -0.022       0.272
shops                                         0.0623      0.211      0.295      0.768      -0.352       0.477
offices                                      -0.2244      0.376     -0.597      0.551      -0.962       0.513
water_distance                             -5.23e-07   5.63e-07     -0.928      0.353   -1.63e-06    5.82e-07
==============================================================================
Omnibus:                      131.562   Durbin-Watson:                   0.860
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              172.834
Skew:                           0.892   Prob(JB):                     2.95e-38
Kurtosis:                       2.872   Cond. No.                     1.73e+22
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 7.13e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

time: 156 ms (started: 2026-02-25 12:42:17 +13:00)